/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

/* Variables */
extern int __io_putchar(int ch) __attribute__((weak)); // NOLINT
extern int __io_getchar(void) __attribute__((weak));   // NOLINT

char *__env[1] = {0};   // NOLINT
char **environ = __env; // NOLINT

/* Functions */
void initialise_monitor_handles(void)
{
}

int _getpid(void) // NOLINT
{
  return 1;
}

int _kill(int pid, int sig) // NOLINT
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit(int status) // NOLINT
{
  _kill(status, -1);
  while (1)
  {
  } /* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len) // NOLINT
{
  (void)file;
  int DataIdx = 0;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = (char)__io_getchar();
  }

  return len;
}

__attribute__((weak)) int _write(int file, char *ptr, int len) // NOLINT
{
  (void)file;
  int DataIdx = 0;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

int _close(int file) // NOLINT
{
  (void)file;
  return -1;
}

int _fstat(int file, struct stat *file_stat) // NOLINT
{
  (void)file;
  file_stat->st_mode = S_IFCHR;
  return 0;
}

int _isatty(int file) // NOLINT
{
  (void)file;
  return 1;
}

int _lseek(int file, int ptr, int dir) // NOLINT
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _open(const char *path, int flags, ...) // NOLINT
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

int _wait(const int *status) // NOLINT
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(const char *name) // NOLINT
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _times(struct tms *buf) // NOLINT
{
  (void)buf;
  return -1;
}

int _stat(const char *file, struct stat *st) // NOLINT
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(const char *old, const char *new) // NOLINT
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void) // NOLINT
{
  errno = EAGAIN;
  return -1;
}

int _execve(const char *name, char **argv, char **env) // NOLINT
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
