arch:
  thumbv6:
    processor: ["cortex-m0", "cortex-m0plus", "cortex-m1"]

  thumbv7:
    float_abi: ["soft", "softfp", "hard"]
    fpu: ["auto", "vfpv4", "fpv4-d16", "fpv4-sp-d16", "fpv5-sp-d16", "fpv5-d16"]
    processor: ["cortex-m3", "cortex-m4", "cortex-m7"]

  thumbv8:
    float_abi: ["soft", "softfp", "hard"]
    processor:
      ["cortex-m23", "cortex-m33", "cortex-m35p", "cortex-m55", "cortex-m85"]
